name: frontend_delpick
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # HTTP & API
  dio: ^5.4.0

  # Local Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3

  # Real-time Communication
  socket_io_client: ^2.0.3

  # Image Handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  image: ^4.1.7

  # UI Components
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0

  # Push Notifications
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.3.0

  sqflite: ^2.3.0
  path: ^1.8.3

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7

  firebase_core: ^2.20.0
  connectivity_plus: ^5.0.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  share_plus: ^7.2.1



dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
